# Generated by Django 4.1 on 2022-08-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apliecommerce', '0003_produtodest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoDest',
        ),
    ]
