# Generated by Django 4.1 on 2022-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliecommerce', '0004_delete_produtodest'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='texto',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
